---
# tasks file for virtualbox

- name: Configure VirtualBox APT-Key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - "https://www.virtualbox.org/download/oracle_vbox.asc"
  become: true

- name: Configure VirtualBox APT repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  become: true

- name: Install virtualbox
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - dkms
    - virtualbox-{{ virtualbox_major_version }}.{{ virtualbox_minor_version }}
  become: true

- name: Check VirtualBox-Version installed
  shell: |
    version = $(VBoxManage -v)
    maj_version = $(echo $version | cut -d 'r' -f 1)
    echo $maj_version
  register: installed_vboxversion
  changed_when: false

- name: Check installed ExtPack
  shell: VBoxManage list extpacks
  register: installed_extpacks
  changed_when: 'installed_extpacks.stdout == "Extension Packs: 0"'

- name: Download Extensionpack
  get_url:
    url: http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack
    dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack
    mode: 0664

- name: Install Extensionpack
  command: VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack --accept-license={{ virtualbox_extpack_license }}
  become: true
