---
#deb http://deb.torproject.org/torproject.org xenial main
#deb-src http://deb.torproject.org/torproject.org xenial main
#gpg --keyserver keys.gnupg.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
#gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89)
  become: yes
  apt_key:
    #data: "{{ lookup('file', 'torproject.gpg') }}"
    keyserver: keys.gnupg.net
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: Ensure torproject.org repository is present (APT)
  become: yes
  apt_repository:
    repo: 'deb http://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: Install tor
  become: yes
  notify: restart tor
  apt:
    name: tor
    state: present
    update_cache: yes

- name: Config TOR
  become: yes
  notify: restart tor
  template:
    src: torrc.j2
    dest: /etc/tor/torrc
    owner: root
    group: root
