---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ vmcloak_apt_requirements }}"
  become: yes


- name: Install vmcloak
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv_python: python2.7
    virtualenv: "{{ cuckoo_working_directory }}/venv_vmcloak"
  with_items: "{{ vmcloak_pip_packages }}"
  become: yes
  become_user: "{{ cuckoo_user }}"
